export const resortData = {
  name: "Aaryam Resorts",
  tagline: "Where Luxury Meets Nature",
  location: "Nainital, Uttarakhand, India",
  established: 2010,
  contact: {
    phone: "+91 98765 43210",
    email: "stay@aaryamresorts.com",
    address: "Valley of Flowers Road, Nainital, Uttarakhand 263001",
  },
  policies: {
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    breakfastIncluded: true,
    petFriendly: false,
    smokingAllowed: false,
    cancellation: "Free cancellation up to 48 hours before check-in",
  },
  rooms: [
    {
      id: "deluxe",
      name: "Deluxe Room",
      price: 5000,
      currency: "INR",
      capacity: 2,
      description:
        "Elegant mountain-view room with modern luxury amenities, perfect for couples or solo travelers seeking comfort.",
      amenities: [
        "King Bed",
        "Mountain View",
        "55-inch Smart TV",
        "Mini Bar",
        "Premium En-suite Bathroom",
        "High-Speed WiFi",
        "Room Service",
        "Air Conditioning",
      ],
      highlight: "Best value with stunning mountain views",
    },
    {
      id: "family",
      name: "Family Suite",
      price: 9000,
      currency: "INR",
      capacity: 4,
      description:
        "Spacious suite with a separate living area and kitchenette, designed for families seeking space and comfort.",
      amenities: [
        "2 Bedrooms",
        "Separate Living Room",
        "Kitchenette",
        "Private Balcony",
        "Jacuzzi",
        "Kids Play Area",
        "55-inch Smart TV",
        "Premium WiFi",
      ],
      highlight: "Perfect for families with children",
    },
    {
      id: "honeymoon",
      name: "Honeymoon Suite",
      price: 12000,
      currency: "INR",
      capacity: 2,
      description:
        "Romantic premium suite with panoramic valley views, exclusive services, and unforgettable romantic experiences.",
      amenities: [
        "King Canopy Bed",
        "Panoramic Valley View",
        "Private Jacuzzi",
        "Rose Petal Turndown",
        "Private Terrace",
        "Butler Service",
        "Champagne on Arrival",
        "Couple Spa Access",
      ],
      highlight: "Ultimate romantic getaway experience",
    },
  ],
  amenities: [
    "Infinity Swimming Pool",
    "Multi-Cuisine Restaurant",
    "Free High-Speed WiFi",
    "Evening Campfire",
    "Travel Desk & Concierge",
    "Guided Nature Tours",
    "Yoga & Meditation Center",
    "Spa & Wellness Center",
    "Conference & Event Hall",
    "Airport Transfers",
    "Library & Reading Lounge",
    "Bicycle Rentals",
  ],
  activities: [
    "Mountain Trekking",
    "Nature Photography Walks",
    "Birdwatching Sessions",
    "Campfire & Bonfire Nights",
    "Sunrise Yoga Sessions",
    "Cultural Evening Programs",
    "Rock Climbing",
    "River Rafting (seasonal)",
    "Star Gazing",
    "Cooking Classes",
  ],
  nearbyAttractions: [
    {
      name: "Snow View Point",
      distance: "5 km",
      type: "Scenic",
      description: "Panoramic Himalayan views with snow-capped peaks",
    },
    {
      name: "Sattal Lake",
      distance: "8 km",
      type: "Nature",
      description: "Serene cluster of seven interconnected lakes",
    },
    {
      name: "Bhimtal Waterfalls",
      distance: "6 km",
      type: "Nature",
      description: "Stunning cascading waterfalls through dense forest",
    },
    {
      name: "Naini Peak Trek",
      distance: "2 km start",
      type: "Adventure",
      description: "Challenging trek to highest peak in Nainital",
    },
    {
      name: "Sunset Peak",
      distance: "10 km",
      type: "Scenic",
      description: "Best spot to witness breathtaking Himalayan sunsets",
    },
    {
      name: "Mall Road Nainital",
      distance: "3 km",
      type: "Shopping",
      description: "Famous shopping street with local crafts and cuisine",
    },
    {
      name: "Nainital Zoo",
      distance: "4 km",
      type: "Family",
      description: "Home to rare Himalayan wildlife and exotic birds",
    },
    {
      name: "Eco Cave Gardens",
      distance: "7 km",
      type: "Adventure",
      description: "Interconnected natural caves and hanging gardens",
    },
  ],
  packages: [
    {
      id: "romantic",
      name: "Romantic Escape",
      price: 28000,
      duration: "2 nights / 3 days",
      forTypes: ["Honeymoon"],
      room: "Honeymoon Suite",
      includes: [
        "Honeymoon Suite accommodation",
        "Candlelight dinner for two",
        "Couple spa session",
        "Sunrise guided tour",
        "Champagne & welcome basket",
        "All breakfasts",
      ],
      description:
        "The ultimate romantic mountain retreat for couples and honeymooners",
    },
    {
      id: "family",
      name: "Family Adventure",
      price: 22000,
      duration: "2 nights / 3 days",
      forTypes: ["Family Vacation"],
      room: "Family Suite",
      includes: [
        "Family Suite accommodation",
        "All meals included",
        "Guided mountain trek",
        "Cultural evening show",
        "Kids activities",
        "Airport transfers",
      ],
      description:
        "Fun-filled mountain escape with activities for every family member",
    },
    {
      id: "solo",
      name: "Solo Explorer",
      price: 12000,
      duration: "2 nights / 3 days",
      forTypes: ["Solo Travel"],
      room: "Deluxe Room",
      includes: [
        "Deluxe Room accommodation",
        "All breakfasts",
        "Guided nature trek",
        "Photography tour",
        "Yoga & meditation session",
        "Travel desk assistance",
      ],
      description:
        "Perfect solo adventure for explorers, nature lovers and photographers",
    },
    {
      id: "friends",
      name: "Friends Fiesta",
      price: 18000,
      duration: "2 nights / 3 days",
      forTypes: ["Friends Trip"],
      room: "Deluxe Rooms",
      includes: [
        "Deluxe Room accommodation (per person)",
        "Campfire nights",
        "Adventure activities",
        "Group trek",
        "BBQ dinner",
        "Star gazing session",
      ],
      description: "Epic group escape with adventures and unforgettable memories",
    },
    {
      id: "corporate",
      name: "Executive Retreat",
      price: 45000,
      duration: "3 nights / 4 days",
      forTypes: ["Corporate Retreat"],
      room: "Multiple Deluxe Rooms",
      includes: [
        "Multiple room accommodation",
        "Conference hall access",
        "Team-building activities",
        "All meals included",
        "Networking dinner",
        "Corporate adventure activities",
      ],
      description:
        "Premium corporate retreat combining productivity with mountain luxury",
    },
  ],
  dining: {
    restaurant: "The Summit Bistro",
    cuisine: ["North Indian", "Continental", "Chinese", "Uttarakhandi Cuisine"],
    specialties: [
      "Kumaoni Raita",
      "Mountain Dal Bhat",
      "Forest Mushroom Risotto",
      "Himalayan Trout",
    ],
    timings: {
      breakfast: "7:00 AM - 10:30 AM",
      lunch: "12:30 PM - 3:00 PM",
      dinner: "7:00 PM - 10:30 PM",
    },
  },
};

export type Room = (typeof resortData.rooms)[0];
export type Package = (typeof resortData.packages)[0];
export type Attraction = (typeof resortData.nearbyAttractions)[0];
